name: pias_laundry_customer
description: Flutter customer app for Pia's Laundry Shop.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  flutter_map: ^8.3.2
  geolocator: ^14.1.1
  geolocator_android: ^5.1.1+1
  http: ^1.6.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
